name: app_4030_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.4
  logger: ^2.6.1
  dio: ^5.9.0
  dio_handler: ^0.0.2
  either_dart: ^1.0.0
  flutter_gen: ^5.11.0
  build_runner:
  flutter_gen_runner:
  http: ^1.5.0
  fl_chart: ^0.70.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pngs/
    - assets/fonts/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Bold.ttf
          weight: 900
        - asset: assets/fonts/YekanBakh-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakh-Regular.ttf
          weight: 500
        - asset: assets/fonts/YekanBakh-Light.ttf
          weight: 300
        - asset: assets/fonts/YekanBakh-Thin.ttf
          weight: 100

scripts: derry.yaml

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"